version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  auth:
    build: ./auth
    container_name: auth
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  event:
    build: ./event
    container_name: event
    ports:
      - '4001:4001'
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - '3300:3300'
    environment:
      - NODE_ENV=production
    depends_on:
      - auth
      - event

volumes:
  mongo_data:
